apiVersion: kustomize.config.k8s.io/v1beta1
kind: Kustomization

namespace: im

resources:
  - namespace.yaml
  - configmap.yaml
  - secret.yaml
  - api-gateway.yaml
  - api-gateway-hpa.yaml
  - delivery-service.yaml
  - delivery-service-hpa.yaml
  - wsbench.yaml

labels:
  - pairs:
      app.kubernetes.io/part-of: im-system
      app.kubernetes.io/managed-by: kustomize
    includeSelectors: false
