apiVersion: v1
kind: Secret
metadata:
  name: im-secrets
  namespace: im
type: Opaque
stringData:
  # MySQL 密码
  MYSQL_PASSWORD: "imdev"
  MYSQL_DSN: "root:imdev@tcp(mysql:3306)/im_db?charset=utf8mb4&parseTime=True&loc=Local"
  
  # JWT 密钥
  JWT_SECRET: "your-production-jwt-secret-key-at-least-32-characters"
  
  # MinIO 凭证
  MINIO_ACCESS_KEY: "admin"
  MINIO_SECRET_KEY: "admin123"
