# API Gateway 本地开发配置（Docker 网络）
server:
  http_port: 8080
  grpc_addr_identity: "identity-service:9080"
  grpc_addr_conversation: "conversation-service:9081"
  grpc_addr_message: "message-service:9082"
  http_addr_message: "http://message-service:8083"
  grpc_addr_presence: "presence-service:9084"
  grpc_addr_file: "file-service:9085"
  grpc_timeout: 5s
  read_timeout: 30s
  write_timeout: 30s

jwt:
  secret: "dev-jwt-secret-key-at-least-32-characters"

log:
  service: "api-gateway"
  level: debug
  encoding: console
  stdout: true
  file:
    path: ""
